[package]
name = "zipf"
version = "5.0.1"
readme = "./README.md"
description = "A fast generator of discrete, bounded Zipf-distributed random numbers"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

license = "Apache-2.0"
keywords = ["random", "distribution", "zipf"]
categories = ["algorithms"]

repository = "https://github.com/jonhoo/rust-zipf"
documentation = "https://docs.rs/zipf"

[badges]
travis-ci = { repository = "jonhoo/rust-zipf" }
maintenance = { status = "passively-maintained" }

[dependencies]
rand = "0.6.0"

[dev-dependencies]
randomkit = "0.1"
